INSERT INTO tags (label) VALUES 
('Footwear'),
('Outdoor Apparel'),
('Fresh Produce'),
('Beverages'),
('Cutlery'),
('Electronics'),
('Home Appliances'),
('Furniture'),
('Toys'),
('Books'),
('Beauty Products'),
('Health and Wellness'),
('Office Supplies'),
('Cleaning Supplies'),
('Pet Supplies'),
('Sports Equipment'),
('Fitness Gear'),
('Automotive Accessories'),
('Baby Products'),
('Gardening Tools'),
('Kitchen Appliances'),
('Mobile Accessories'),
('Computer Accessories'),
('Musical Instruments'),
('Jewelry'),
('Watches'),
('Bags and Luggage'),
('Stationery'),
('Lighting'),
('Decor'),
('Bedding'),
('Bath Supplies'),
('Travel Accessories'),
('Art Supplies'),
('Craft Materials'),
('Party Supplies'),
('Safety Equipment'),
('Seasonal Products'),
('Toys and Games'),
('Video Games'),
('Camping Gear'),
('Survival Gear'),
('Hiking Equipment'),
('Skincare Products'),
('Hair Care Products'),
('Dairy Products'),
('Meat and Poultry'),
('Seafood'),
('Organic Produce'),
('Grains and Cereals'),
('Vegetables'),
('Fruits'),
('Herbs and Spices'),
('Canned Goods'),
('Frozen Foods'),
('Bakery Items'),
('Confectionery'),
('Snacks'),
('Nuts and Seeds'),
('Vegan Products'),
('Gluten-Free Products'),
('Non-Alcoholic Beverages'),
('Alcoholic Beverages'),
('Juices'),
('Soft Drinks'),
('Coffee and Tea'),
('Plant-Based Meats'),
('Honey and Jams'),
('Condiments and Sauces'),
('Olive Oil'),
('Sunflower Oil'),
('Vinegar'),
('Agricultural Tools'),
('Seeds and Fertilizers'),
('Livestock Feed');