"""empty message

Revision ID: 2642fa58e8cb
Revises: a4a6080d70f9
Create Date: 2024-10-18 04:58:08.072812

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2642fa58e8cb"
down_revision = "a4a6080d70f9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("country", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country"],
            ["countries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cities_country"), "cities", ["country"], unique=False)
    op.create_index(
        op.f("ix_documents_uploader_id"), "documents", ["uploader_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_applications_applicant_id"),
        "event_applications",
        ["applicant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_applications_event_id"),
        "event_applications",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_events_organizer_id"), "events", ["organizer_id"], unique=False
    )
    op.create_index(
        op.f("ix_organization_rating_target_org"),
        "organization_rating",
        ["target_org"],
        unique=False,
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(
        op.f("ix_organization_rating_target_org"), table_name="organization_rating"
    )
    op.drop_index(op.f("ix_events_organizer_id"), table_name="events")
    op.drop_index(
        op.f("ix_event_applications_event_id"), table_name="event_applications"
    )
    op.drop_index(
        op.f("ix_event_applications_applicant_id"), table_name="event_applications"
    )
    op.drop_index(op.f("ix_documents_uploader_id"), table_name="documents")
    op.drop_index(op.f("ix_cities_country"), table_name="cities")
    op.drop_table("cities")
    op.drop_table("countries")
    # ### end Alembic commands ###
