"""empty message

Revision ID: 3a27571d23b6
Revises: 7dda247edd0b
Create Date: 2024-10-17 04:43:05.975477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a27571d23b6'
down_revision = '7dda247edd0b'
branch_labels = None
depends_on = None

gender_enum = sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNDISCLOSED', name='gender_enum', create_type=False)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('gender', gender_enum, nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'gender')
    gender_enum.drop(op.get_bind())
    # ### end Alembic commands ###
