"""empty message

Revision ID: 3d1c618c01e8
Revises: f718dfbfda00
Create Date: 2024-10-18 11:55:04.403236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1c618c01e8'
down_revision = 'f718dfbfda00'
branch_labels = None
depends_on = None

org_size_enum = sa.Enum('LARGE', 'MEDIUM', 'SMALL', name='organization_size', create_type=False)

def upgrade() -> None:
    org_size_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=False))
    op.add_column('organizations', sa.Column('size', org_size_enum, nullable=False))
    op.add_column('organizations', sa.Column('years_of_operation', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'years_of_operation')
    op.drop_column('organizations', 'size')
    op.drop_column('organizations', 'email')
    org_size_enum.drop(op.get_bind())
    # ### end Alembic commands ###
