"""empty message

Revision ID: a4a6080d70f9
Revises: 3a27571d23b6
Create Date: 2024-10-17 07:42:39.987827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a6080d70f9'
down_revision = '3a27571d23b6'
branch_labels = None
depends_on = None

org_type_enum = sa.Enum('EVENT_ORGANIZER', 'VENDOR', name='organization_type', create_type=False)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    org_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('organizations', sa.Column('organization_type', org_type_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'organization_type')
    org_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
