"""empty message

Revision ID: d0b662b367e8
Revises: 2642fa58e8cb
Create Date: 2024-10-18 07:40:28.917488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0b662b367e8'
down_revision = '2642fa58e8cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer, autoincrement=False, nullable=True))
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
