"""empty message

Revision ID: f718dfbfda00
Revises: d0b662b367e8
Create Date: 2024-10-19 22:54:10.819156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f718dfbfda00'
down_revision = 'd0b662b367e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('events', sa.Column('status', sa.Enum('HIDDEN', 'PUBLIC', name='event_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'status')
    op.drop_column('events', 'tags')
    # ### end Alembic commands ###
