"""empty message

Revision ID: fb8924fb8812
Revises: 91a7f91e22b8
Create Date: 2024-10-21 13:26:44.880436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8924fb8812'
down_revision = '91a7f91e22b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
